# Generated by Django 2.2 on 2023-04-27 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0002_auto_20230427_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='user',
        ),
    ]
