# Generated by Django 2.2 on 2023-04-27 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0003_auto_20230427_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='category',
        ),
    ]
