# Generated by Django 2.2 on 2023-05-04 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0007_goal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='goal',
            name='category',
            field=models.CharField(choices=[('savings', 'Savings'), ('investments', 'Investments'), ('debt_reduction', 'Debt Reduction')], default='savings', max_length=20),
        ),
        migrations.AlterField(
            model_name='goal',
            name='description',
            field=models.TextField(),
        ),
    ]
