# Generated by Django 2.2 on 2023-05-04 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0008_auto_20230504_0334'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='current_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
