# Generated by Django 2.2 on 2023-05-04 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0009_goal_current_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='source',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
