# Generated by Django 2.2 on 2023-04-26 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='profilepic.jpg', upload_to='profile_pictures/'),
        ),
    ]
